os: Visual Studio 2017
install:

before_build:
- cmd: git submodule update --init --recursive

build_script:
- cmd: dotnet --info
- ps: .\build.ps1 -Platform "AnyCPU" -Configuration "Release"

test: off

artifacts:
- path: artifacts/zips/*.zip